language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
      - POST_INSTALL_HOOK="ocaml pkg/pkg.ml build -v && ocaml pkg/pkg.ml test -v"
      - PACKAGE=topkg
  matrix:
      - OCAML_VERSION=4.01
      - OCAML_VERSION=4.02
      - OCAML_VERSION=4.03
      - OCAML_VERSION=4.04
      - OCAML_VERSION=4.05
os:
  - linux
  - osx
