#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action lib-native; action bin-native ;;
        bin-byte)   $OCAMLBUILD topkg_bin.byte
                    $OCAMLBUILD toy_github_delegate.byte ;;
        bin-native) $OCAMLBUILD topkg_bin.native
                    $OCAMLBUILD toy_github_delegate.native ;;
        lib-byte)   $OCAMLBUILD topkg.cma topkg_care.cma ;;
        lib-native) $OCAMLBUILD topkg.cmxa topkg_care.cmxa ;;
        test|tests) $OCAMLBUILD test/tests.otarget ;;
        doc)        shift; topkg doc --dev $*;;
        api-doc)    shift; topkg doc $* ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
