#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action lib-native ;;
        lib-byte)   $OCAMLBUILD topkg.cma ;;
        lib-native) $OCAMLBUILD topkg.cmxa ;;
        test|tests) $OCAMLBUILD test/tests.otarget ;;
        doc)        shift; pkg-doc $* doc/dev-api.docdir ;;
        api-doc)    shift; pkg-doc $* doc/api.docdir ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
